"""
Reusable Starlark macros for setting up both the local Bazel WORKSPACE, and also for preparing other
workspaces for importing the protos defined in this project. See the README for more details on
importing this repository in other Bazel workspaces.
"""

load("//defs:defs.bzl", "define_buildifier_tests")

define_buildifier_tests()
