"""
The top-level directory for the Oppia proto API. Generally, no actual proto libraries should be
defined at this level. Instead, protos should go into the corresponding version in which they
belong. See the README for more details on the API is versioned.
"""
